"Generated by paket2bazel"

load("@rules_dotnet//dotnet/private/rules/nuget:nuget_repo.bzl", "nuget_repo")
load("@rules_dotnet//dotnet:nuget-lock.bzl", "packages")

def rules_dotnet_nuget_packages():
    "rules_dotnet_nuget_packages"
    nuget_repo(
        name = "rules_dotnet_nuget_packages",
        packages = packages,
    )
